### ISSUE TITLE
Email reports should include renewals

### ISSUE THREAD

**Issue by rickalday** [impress-org/give-email-reports#61] opened 2020-05-01 18:38 UTC
# Bug Report

## User Story

As a site admin, I want to have accurate email reports that reflect all earnings.

## Current Behavior

The report does not take into account renewals payments.

## Expected Behavior

Include all donations.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Activate Email Report on a site that has subscriptions
2. View Monthly Email Report
3. Compare to GiveWP core Reports

## Visuals

<img width="1151" alt="Screen Shot 2020-05-01 at 1 17 48 PM" src="https://user-images.githubusercontent.com/312000/80831389-54b6ea00-8bb0-11ea-89df-3201746c32fc.png">

## Related

https://secure.helpscout.net/conversation/1157789138/64811/
https://secure.helpscout.net/conversation/1213049522/69178/

## Acceptance Criteria

- [ ] Email report accurately reflects number donations and totals.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X | Microsoft Windows | Linux | Android | iOS</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    
</details>

**Comment by lindseymacmillan** [comment] 2020-07-14 22:57
Update 7/14/20:

After looking into this issue some more, and testing a few different theories it looks like the bug is produced by a messy race-condition that exists within the `give_get_earning` and `give_get_sales` methods of the Give_Payment_Stats object. 

The functions used to get the Report totals in this Addon rely on the GiveWP core payment stats object to query payments and generate the totals. By default, the Give Payment Stats object setups up a post query arguments array to query payments with status `publish`. Before this argument array is used to actually query anything, the `give_stats_earnings_args` filter is applied to it. Theoretically, this is where the Give Recurring Donation hooks in to filter the query args so that the status arg is changed to an array containing `publish` and `give_subscription` (ensuring that renewals are also queried and included in earnings/sales totals). 

However, in practice this happens with some inconsistency. In my first testing, email reports included renewals in their totals only occasionally (and only if I also made sure to purge the Give Cache between sending test emails). Then, I tried deactivating and reactivating the email report addon and recurring donations addon. This fixed the issue, but isn't a real solution.

I'm assigning @ravinderk to this issue as well to get his eyes on it, and see if he is able to replicate my findings or has suggestions in how to better ensure that the query args are filtered consistently. 

cc: @rickalday @Benunc

**Comment by kevinwhoffman** [comment] 2020-07-17 04:22
@ravinderk Please assist Henry on this urgent issue. He has provided some valuable insight in https://github.com/impress-org/give-email-reports/issues/61#issuecomment-658452843.

Let's prioritize a resolution or at least a status update by end of day Friday.

**Comment by ravinderk** [comment] 2020-07-17 20:10
@rickalday I find out that renewals add to email (send by corn job) but not in preview email because `Recurring` addon register `give_subcription` post status on `wp_loaded` hook but preview email renders on `init` hook which fires before `wp_loaded` that means when we render preview email WordPress is not able to recognize `give_subscription` and exclude it from the final SQL query.

https://github.com/impress-org/give-recurring/blob/3b564d7cb73e8de06df5f721200d67a55957280d/give-recurring.php#L418
https://github.com/impress-org/givewp/blob/db1380ba892df586096cc792fc76b92475e0faf3/includes/admin/emails/class-email-notifications.php#L77.

**Comment by kevinwhoffman** [comment] 2020-07-17 20:44
@ravinderk Your feedback suggests that the email reports are accurate when they are sent to the user's inbox, and the preview email in GiveWP dashboard is the only place where the reported total is inaccurate.

@henryholtgeerts @ravinderk Have you seen the inaccurate totals in an actual email, or only in the dashboard preview? We need to confirm the scope of this issue.

**Comment by JasonTheAdams** [comment] 2020-07-17 21:24
@ravinderk When you say "preview email" are you referring to an email previewed _within_ the admin dashboard? Or an email as the result of triggering a test email to be sent? If the latter, then I believe what you're saying is:
- Works: Email that is sent via cron
- Fails: Email that is sent via "send test email"
- Fails: Email displayed via "Preview"

**Comment by lindseymacmillan** [comment] 2020-07-17 21:53
@JasonTheAdams Just did further testing locally, and I can confirm that your summary here is accurate (regarding scope of the issue). However, I don't have access to the HelpScout conversations related to this, so I'm not sure under exactly what conditions renewals were not factoring into email reports for customers. If the HelpScout conversations reveal that customers were not getting accurate totals, even when the email was sent via the cron job, then there may be something else failing here.

**Comment by kevinwhoffman** [comment] 2020-07-20 14:31
@Benunc has confirmed that the customer feedback shows the problem exists with "real" emails sent via cron. I've also looked into the feedback in Help Scout and found [one example](https://secure.helpscout.net/conversation/1157789138/64811/#thread-3491595970) where they attached an email that was clearly exported from Outlook.

There is [another example](https://secure.helpscout.net/conversation/1213049522/69178/#thread-3463279937) where they forwarded the actual email to us.

This suggests that the summary provided in https://github.com/impress-org/give-email-reports/issues/61#issuecomment-660343933 does not match the customer report and that this issue extends beyond the email preview into the emails sent by cron.

**Comment by kevinwhoffman** [comment] 2020-07-21 16:32
After discussing with @Benunc and @DevinWalker, the underlying cause for the customer's inaccurate email reports may be related to Authorize.net delays and not actually due to missing renewals in the report.

We've had two developers confirm the following behavior. To be clear, there is a bug causing inaccurate email report _previews_, however this is not urgent and will be addressed in cooldown.

**Comment by kevinwhoffman** [comment] 2020-08-12 17:29
Several developers have looked into this and we are not able to replicate it consistently. We're going to close this out.

**Closed as completed by kevinwhoffman** 2020-08-12 17:29 UTC
Labels: type: bug
